# Generated by Django 4.2.6 on 2023-10-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulecell',
            unique_together={('day_of_week', 'lesson_number', 'schedule_number')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulecell'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson'),
        ),
    ]
