# Generated by Django 4.2.6 on 2023-10-05 10:02

from django.db import migrations, models

def create_schedule_cells(apps, schema_editor):
    ScheduleCell = apps.get_model('schedule', 'ScheduleCell')
    for schedule_number in range(1, 3):
        for lesson_number in range(1, 9):
            for day_of_week in range(0, 7):
                ScheduleCell.objects.create(
                    schedule_number=schedule_number,
                    lesson_number=lesson_number,
                    day_of_week=day_of_week
                )


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_room_number'),
    ]

    operations = [
        migrations.RunPython(
            code=create_schedule_cells,
            reverse_code=migrations.RunPython.noop
        )
    ]
