# Generated by Django 4.2.6 on 2023-10-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_CREATE_SCHEDULE_CELLS'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('lesson', 'deadline')},
        ),
    ]
